certstream:
  enable: true
  topics:
    - "zdns"
zdns:
  enable: false
  ipv4: true
  ipv6: false
  topics:
    - "zdns_4hr"
    - "zdns_8hr"
zgrab:
  enable: true
  topics:
    - "zgrab_4hr"
    - "zgrab_8hr"
monitor:
  storage: "."
  name: "sentinel-stats"
datastore:
  storage: "."