certstream:
  enable: true
  topics:
    - "certstream"
zdns:
  enable: true
  ipv6: false
  topics:
    - "zdns_4hr"
    - "zdns_24hr"
zgrab:
  enable: true
  topics:
    - "zgrab_4hr"
    - "zgrab_24hr"