certstream:
  enable: true
  topics:
    - "zdns"
zdns:
  enable: true
  ipv4: true
  ipv6: false
  topics:
    - "zdns_4hr"
zgrab:
  enable: true
  topics:
    - "zgrab_4hr"
monitor:
  storage: "/mnt/projects/zdns/sentinel"
  name: "sentinel-stats"
